//
// Created by chris on 23/11/2021.
//

#ifndef MEM_GREP_LIB_DATASTRUCTURE_DETECTION_STRINGDETECTOR_HPP_
#define MEM_GREP_LIB_DATASTRUCTURE_DETECTION_STRINGDETECTOR_HPP_

class stringdetector {};

#endif	// MEM_GREP_LIB_DATASTRUCTURE_DETECTION_STRINGDETECTOR_HPP_
